# Generated by Django 5.2.17 on 2026-09-30 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('SQL', 'sql')], max_length=120)),
            ],
            options={
                'verbose_name': 'competence',
                'verbose_name_plural': 'competences',
            },
        ),
        migrations.CreateModel(
            name='EnseignantReferent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'personne',
                'verbose_name_plural': 'personnes',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('matricule', models.CharField(max_length=120)),
                ('promotion', models.PositiveSmallIntegerField(help_text='2026')),
                ('competences', models.ManyToManyField(related_name='etudiants', to='stages.competence')),
            ],
            options={
                'verbose_name': 'etudiant',
                'verbose_name_plural': 'etudiants',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField()),
                ('description', models.CharField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_places', models.PositiveSmallIntegerField()),
                ('competences', models.ManyToManyField(related_name='offres', to='stages.competence')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='stages.entreprise')),
            ],
            options={
                'verbose_name': 'offre',
                'verbose_name_plural': 'offres',
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depot', models.DateField()),
                ('statut', models.CharField(choices=[('déposée', 'Deposee'), ('refuseé', 'Refusee'), ('retenue', 'Retenu')])),
                ('etudiants', models.ManyToManyField(related_name='candidatures', to='stages.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='stages.offre')),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
            },
        ),
        migrations.CreateModel(
            name='TuteurEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuteurs', to='stages.entreprise')),
            ],
            options={
                'verbose_name': 'personne',
                'verbose_name_plural': 'personnes',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField()),
                ('candidature', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage', to='stages.candidature')),
                ('enseigant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.enseignantreferent')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.entreprise')),
                ('etudiants', models.ManyToManyField(related_name='stages', to='stages.etudiant')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.tuteurentreprise')),
            ],
            options={
                'verbose_name': 'stage',
                'verbose_name_plural': 'stages',
            },
        ),
    ]
