# Generated by Django 5.2.17 on 2026-09-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_competence_enseignantreferent_etudiant_offre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='libelle',
            field=models.CharField(choices=[('SQL', 'sql'), ('fastapi', 'Fastapi'), ('python', 'Python'), ('django', 'Django'), ('laravel', 'Laravel')], max_length=120),
        ),
    ]
