# Generated by Django 5.2.17 on 2026-10-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_alter_competence_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='libelle',
            field=models.CharField(choices=[('fastapi', 'Fastapi'), ('python', 'Python'), ('django', 'Django'), ('laravel', 'Laravel'), ('JAVA', 'Java'), ('C', 'C'), ('PHP', 'PHP'), ('HTML_CSS', 'HTML / CSS'), ('JAVASCRIPT', 'JavaScript'), ('SQL', 'SQL'), ('POSTGRESQL', 'PostgreSQL'), ('MYSQL', 'MySQL'), ('GIT', 'Git & GitHub'), ('LINUX', 'Linux / Systèmes'), ('RESEAUX', 'Bases des réseaux (TCP/IP)'), ('ALGORITHMIQUE', 'Algorithmique & Structures de données')], max_length=120),
        ),
    ]
