# Generated by Django 5.2.17 on 2026-10-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_alter_competence_libelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='etudiants',
        ),
        migrations.AddField(
            model_name='candidature',
            name='etudiants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='stages.etudiant'),
        ),
    ]
