# Generated by Django 5.2.17 on 2026-10-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_remove_candidature_etudiants_candidature_etudiants'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignantreferent',
            name='sexe',
            field=models.CharField(choices=[('F', 'Femme'), ('M', 'Homme')], null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(choices=[('F', 'Femme'), ('M', 'Homme')], null=True),
        ),
        migrations.AddField(
            model_name='tuteurentreprise',
            name='sexe',
            field=models.CharField(choices=[('F', 'Femme'), ('M', 'Homme')], null=True),
        ),
    ]
