# Generated by Django 5.2.17 on 2026-10-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_enseignantreferent_sexe_etudiant_sexe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='enseigant',
            new_name='enseignant',
        ),
    ]
