# Generated by Django 5.2.17 on 2026-10-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0007_rename_enseigant_stage_enseignant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidature',
            old_name='etudiants',
            new_name='etudiant',
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('etudiant', 'offre'), name='canditater_une_seule_foix_a_une_offre'),
        ),
    ]
